default_language_version:
  python: python3.9
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-merge-conflict
      - id: debug-statements
      - id: trailing-whitespace
  - repo: https://github.com/psf/black/
    rev: 21.5b0
    hooks:
      - id: black
  - repo: https://gitlab.com/pycqa/flake8/
    rev: 3.9.2
    hooks:
      - id: flake8
  - repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
      - id: isort
        name: isort
  - repo: local
    hooks:
      - id: tox
        name: tox-check
        entry: tox .
        language: system
        pass_filenames: false
        always_run: true
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.1.1
    hooks:
      - id: pydocstyle
        name: pydocstyle-check
        entry: pydocstyle .